name: Generate Courses

on:
  push:
    paths:
      - 'gpx_files/**'
      - 'templates/**'
      - 'generate_courses.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate_courses.py
        run: python generate_courses.py

      - name: Set Git identity and remote
        run: |
          echo "Setting Git identity..."
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          echo "Setting remote URL with PAT..."
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/JuliaHazenberg/crits-website.git
          git remote -v
      
      - name: Commit and push generated files
        run: |
          echo "Adding files..."
          git add courses/ index.html || echo "Nothing to add"
          git status
          git commit -m "Auto-generated courses and index" || echo "No changes to commit"
          echo "Pushing changes..."
          git push origin HEAD:main


